INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:training', 'ai', 1, 'Training versus inference', 'https://huggingface.co/learn/llm-course/chapter1/4', 'https://huggingface.co/learn/llm-course/chapter1/4', 'Hugging Face LLM Course', 'html', 'Explain learned weights versus using a trained model, with one request example.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:tokens', 'ai', 2, 'Tokens and context windows', 'https://huggingface.co/learn/llm-course/chapter2/4', 'https://huggingface.co/learn/llm-course/chapter2/4', 'Hugging Face LLM Course', 'html', 'Explain tokenization, token budgets, and input versus output limits.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:embeddings', 'ai', 3, 'Embeddings and vector representations', 'https://huggingface.co/learn/llm-course/chapter2/4', 'https://huggingface.co/learn/llm-course/chapter2/4', 'Hugging Face LLM Course', 'html', 'Distinguish token embeddings from document embeddings and explain vector similarity.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:attention', 'ai', 4, 'Attention and transformers', 'https://jalammar.github.io/illustrated-transformer/', 'https://jalammar.github.io/illustrated-transformer/', 'Jay Alammar', 'html', 'Explain attention and decoder-only generation intuitively before equations.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:generation', 'ai', 5, 'Generation and unsupported answers', 'https://huggingface.co/learn/llm-course/chapter1/4', 'https://huggingface.co/learn/llm-course/chapter1/4', 'Hugging Face LLM Course', 'html', 'Explain next-token prediction, sampling, and why fluent output can be factually wrong.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:model-call', 'ai', 6, 'First model call and expected outcomes', 'https://platform.claude.com/docs/en/build-with-claude/working-with-messages', 'https://platform.claude.com/docs/en/build-with-claude/working-with-messages', 'Anthropic', 'html', 'Explain request messages, output, token usage, and five test cases with expected outcomes.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:prompts', 'ai', 7, 'Prompt construction and examples', 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview', 'https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview', 'Anthropic', 'html', 'Explain explicit tasks, examples, source delimiters, and measurable success criteria.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:structured-output', 'ai', 8, 'Structured outputs and validation', 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs', 'https://platform.claude.com/docs/en/build-with-claude/structured-outputs', 'Anthropic', 'html', 'Explain schemas and why valid JSON does not guarantee correct values.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:streaming', 'ai', 9, 'Streaming and cancellation', 'https://platform.claude.com/docs/en/build-with-claude/streaming', 'https://platform.claude.com/docs/en/build-with-claude/streaming', 'Anthropic', 'html', 'Explain partial output, cancellation, time to first token, and total latency.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:failures', 'ai', 10, 'Timeouts, retries, and rate limits', 'https://platform.claude.com/docs/en/api/errors', 'https://platform.claude.com/docs/en/api/errors', 'Anthropic', 'html', 'Explain bounded retries and handling API errors without repeating unsafe actions.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:eval-sets', 'ai', 11, 'Evaluation sets and held-out cases', 'https://hamel.dev/blog/posts/evals/', 'https://hamel.dev/blog/posts/evals/', 'Hamel Husain', 'html', 'Explain task-specific examples, expected outcomes, and a separate comparison set.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:error-analysis', 'ai', 12, 'Error analysis and failure categories', 'https://hamel.dev/blog/posts/evals/', 'https://hamel.dev/blog/posts/evals/', 'Hamel Husain', 'html', 'Explain inspecting failed traces, grouping causes, and prioritizing frequent mistakes.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:quality-checks', 'ai', 13, 'Deterministic quality checks', 'https://hamel.dev/blog/posts/evals/', 'https://hamel.dev/blog/posts/evals/', 'Hamel Husain', 'html', 'Explain cheap assertions for required fields, allowed actions, and citations.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:judges', 'ai', 14, 'Human review and calibrated LLM judges', 'https://hamel.dev/blog/posts/evals/', 'https://hamel.dev/blog/posts/evals/', 'Hamel Husain', 'html', 'Explain review rubrics and checking automated judges against human labels.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:ingestion', 'ai', 15, 'Document ingestion and chunking', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'Pinecone', 'html', 'Explain extraction, chunk boundaries, overlap, and preserving source provenance.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:retrieval', 'ai', 16, 'Embedding retrieval and relevance', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'Pinecone', 'html', 'Explain query/document encoding, similarity search, and relevance failures.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:vector-indexes', 'ai', 17, 'Vector indexes and authorization filters', 'https://github.com/pgvector/pgvector', 'https://raw.githubusercontent.com/pgvector/pgvector/master/README.md', 'pgvector', 'markdown', 'Explain exact versus approximate retrieval, metadata filters, and access restrictions.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:hybrid-search', 'ai', 18, 'Hybrid lexical and semantic retrieval', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'https://www.pinecone.io/learn/retrieval-augmented-generation/', 'Pinecone', 'html', 'Explain why exact identifiers need lexical matching alongside semantic retrieval.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:reranking', 'ai', 19, 'Reranking and latency trade-offs', 'https://www.pinecone.io/learn/series/rag/rerankers/', 'https://www.pinecone.io/learn/series/rag/rerankers/', 'Pinecone', 'html', 'Explain two-stage retrieval and when extra relevance justifies extra latency.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:rag-evals', 'ai', 20, 'RAG evaluation and unknown answers', 'https://hamel.dev/blog/posts/evals/', 'https://hamel.dev/blog/posts/evals/', 'Hamel Husain', 'html', 'Separate retrieval failures from generation failures and evaluate grounding and citations.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:tools', 'ai', 21, 'Tool calling and application execution', 'https://www.anthropic.com/engineering/building-effective-agents', 'https://www.anthropic.com/engineering/building-effective-agents', 'Anthropic', 'html', 'Explain the model proposing a tool call and application code validating and executing it.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:workflows', 'ai', 22, 'Workflows versus agent loops', 'https://www.anthropic.com/engineering/building-effective-agents', 'https://www.anthropic.com/engineering/building-effective-agents', 'Anthropic', 'html', 'Explain explicit workflows versus dynamic agent loops and bounded execution.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:tool-contracts', 'ai', 23, 'Tool contracts and failures', 'https://www.anthropic.com/engineering/building-effective-agents', 'https://www.anthropic.com/engineering/building-effective-agents', 'Anthropic', 'html', 'Explain clear tool descriptions, validated inputs, useful outputs, and recoverable errors.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:context', 'ai', 24, 'Context management and durable state', 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', 'https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents', 'Anthropic', 'html', 'Explain context selection, summaries, and durable state beyond conversation history.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:agent-evals', 'ai', 25, 'Agent evaluation and human handoffs', 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents', 'https://www.anthropic.com/engineering/demystifying-evals-for-ai-agents', 'Anthropic', 'html', 'Explain trajectory inspection, final-state checks, and human review of consequential actions.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:tracing', 'ai', 26, 'Tracing and sensitive data', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'Chip Huyen', 'html', 'Explain request traces, prompt versions, failure diagnosis, and sensitive-data handling.', '["Observability"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:security', 'ai', 27, 'Prompt injection and least-privilege tools', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'Chip Huyen', 'html', 'Explain untrusted inputs, output checks, permissions, and approvals.', '["Step 2. Put in Guardrails"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:cost', 'ai', 28, 'Model selection, routing, and caching', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'Chip Huyen', 'html', 'Explain model routing and cache choices with cost per successful task.', '["Step 3. Add Model Router and Gateway", "Step 4. Reduce Latency with Cache"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:latency', 'ai', 29, 'Latency, concurrency, and fallbacks', 'https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/reduce-latency', 'https://platform.claude.com/docs/en/test-and-evaluate/strengthen-guardrails/reduce-latency', 'Anthropic', 'html', 'Explain bottleneck measurement, concurrency, timeouts, and fallback quality trade-offs.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('ai:deployment', 'ai', 30, 'Deployment, monitoring, and rollback', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'https://huyenchip.com/2024/07/25/genai-platform.html', 'Chip Huyen', 'html', 'Explain versioned workflows, production monitoring, regression checks, and rollback.', '["AI Pipeline Orchestration"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:http', 'backend', 1, 'HTTP request lifecycle', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview', 'MDN', 'html', 'Explain request/response messages, methods, headers, status codes, and intermediaries.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:api-contracts', 'backend', 2, 'API resources and contracts', 'https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md', 'https://raw.githubusercontent.com/microsoft/api-guidelines/vNext/azure/Guidelines.md', 'Microsoft API Guidelines', 'markdown', 'Explain resource naming, HTTP methods, request schemas, and response contracts.', '["HTTP Request / Response Pattern", "REpresentational State Transfer (REST)"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:validation', 'backend', 3, 'Input validation and error responses', 'https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html', 'https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html', 'OWASP', 'html', 'Explain boundary validation and consistent error responses without leaking internals.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:data-modeling', 'backend', 4, 'Relational data modeling and constraints', 'https://www.postgresql.org/docs/current/ddl-constraints.html', 'https://www.postgresql.org/docs/current/ddl-constraints.html', 'PostgreSQL', 'html', 'Explain tables, primary/foreign keys, uniqueness, and database-enforced invariants.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:queries', 'backend', 5, 'SQL joins and query plans', 'https://www.postgresql.org/docs/current/tutorial-join.html', 'https://www.postgresql.org/docs/current/tutorial-join.html', 'PostgreSQL', 'html', 'Explain combining related tables and how query shape affects work.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:indexes', 'backend', 6, 'Indexes and access patterns', 'https://www.postgresql.org/docs/current/indexes-intro.html', 'https://www.postgresql.org/docs/current/indexes-intro.html', 'PostgreSQL', 'html', 'Explain index lookups, write overhead, and choosing indexes for actual queries.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:transactions', 'backend', 7, 'Transactions and concurrent updates', 'https://www.postgresql.org/docs/current/transaction-iso.html', 'https://www.postgresql.org/docs/current/transaction-iso.html', 'PostgreSQL', 'html', 'Explain atomic transactions, isolation levels, and lost-update risks.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:auth', 'backend', 8, 'Authentication and authorization', 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', 'https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html', 'OWASP', 'html', 'Explain authentication versus authorization, sessions, and secure account handling.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:pagination', 'backend', 9, 'Pagination, filtering, and versioning', 'https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md', 'https://raw.githubusercontent.com/microsoft/api-guidelines/vNext/azure/Guidelines.md', 'Microsoft API Guidelines', 'markdown', 'Explain cursor pagination, predictable filtering, and compatible API changes.', '["Collections", "API Versioning"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:idempotency', 'backend', 10, 'Idempotency and safe retries', 'https://cloud.google.com/storage/docs/retry-strategy?hl=en', 'https://cloud.google.com/storage/docs/retry-strategy?hl=en', 'Google Cloud', 'html', 'Explain safe duplicate handling and why retries can repeat side effects.', '["Overview", "Exponential backoff algorithm", "Retry anti-patterns"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:caching', 'backend', 11, 'Caching and freshness', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching', 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching', 'MDN', 'html', 'Explain cache directives, validation, expiration, and invalidation.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:queues', 'backend', 12, 'Queues and delivery guarantees', 'https://www.rabbitmq.com/docs/confirms', 'https://www.rabbitmq.com/docs/confirms', 'RabbitMQ', 'html', 'Explain acknowledgements, redelivery, publisher confirms, and idempotent consumers.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:backpressure', 'backend', 13, 'Timeouts, rate limits, and backpressure', 'https://sre.google/sre-book/addressing-cascading-failures/', 'https://sre.google/sre-book/addressing-cascading-failures/', 'Google SRE Book', 'html', 'Explain retry budgets, backoff, jitter, and overload protection.', '["Queue Management", "Retries", "Latency and Deadlines"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:observability', 'backend', 14, 'Service observability and debugging', 'https://opentelemetry.io/docs/concepts/signals/', 'https://opentelemetry.io/docs/concepts/signals/', 'OpenTelemetry', 'html', 'Explain logs, metrics, and traces through one failing request.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:security', 'backend', 15, 'API security and tenant boundaries', 'https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html', 'https://cheatsheetseries.owasp.org/cheatsheets/REST_Security_Cheat_Sheet.html', 'OWASP', 'html', 'Explain authorization per resource, input handling, and tenant isolation.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('backend:boundaries', 'backend', 16, 'Scaling and service boundaries', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain stateless services, independent scaling, and the costs of service splits.', '["Application layer"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:requirements', 'systemdesign', 1, 'Requirements and capacity estimates', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain clarifying use cases, scale assumptions, storage, and throughput estimates.', '["How to approach a system design interview question"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:performance', 'systemdesign', 2, 'Latency, throughput, and bottlenecks', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain latency versus throughput and finding the limiting resource.', '["Latency vs throughput"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:network', 'systemdesign', 3, 'DNS, proxies, and load balancing', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain how requests reach servers and how balancing changes failure handling.', '["Load balancer"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:scaling', 'systemdesign', 4, 'Stateless services and horizontal scaling', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain stateless application instances, shared state, and scaling limits.', '["Application layer"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:databases', 'systemdesign', 5, 'Database choice and access patterns', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain relational versus nonrelational storage based on queries and consistency needs.', '["Database"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:indexes', 'systemdesign', 6, 'Indexing and storage trade-offs', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain indexes, query tuning, and read versus write costs.', '["SQL tuning"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:cache', 'systemdesign', 7, 'Caching and invalidation', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain cache-aside, write policies, stale data, and cache failures.', '["Cache"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:consistency', 'systemdesign', 8, 'Replication and consistency', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain weak, eventual, and strong consistency with concrete read/write examples.', '["Consistency patterns"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:sharding', 'systemdesign', 9, 'Partitioning and sharding', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain choosing partition keys, hot shards, and cross-shard work.', '["Sharding"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:queues', 'systemdesign', 10, 'Queues and backpressure', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain asynchronous work, queue growth, acknowledgements, and backpressure.', '["Asynchronism"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:failures', 'systemdesign', 11, 'Distributed failures and retries', 'https://sre.google/sre-book/addressing-cascading-failures/', 'https://sre.google/sre-book/addressing-cascading-failures/', 'Google SRE Book', 'html', 'Explain partial failures, timeouts, idempotency, and jitter.', '["Retries", "Latency and Deadlines"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:coordination', 'systemdesign', 12, 'Coordination and consensus concepts', 'https://etcd.io/docs/v3.6/learning/why/', 'https://etcd.io/docs/v3.6/learning/why/', 'etcd', 'html', 'Explain consensus, leader election, and consistent coordination in distributed key-value stores.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:overload', 'systemdesign', 13, 'Rate limiting and overload protection', 'https://sre.google/sre-book/handling-overload/', 'https://sre.google/sre-book/handling-overload/', 'Google SRE Book', 'html', 'Explain limiting admitted work and avoiding retry amplification.', '["Client-Side Throttling", "Handling Overload Errors"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:reliability', 'systemdesign', 14, 'Observability and disaster recovery', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Explain failover, replicas, availability targets, and recovery trade-offs.', '["Availability patterns"]');
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:shortener', 'systemdesign', 15, 'Case study: URL shortener', 'https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/pastebin/README.md', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/solutions/system_design/pastebin/README.md', 'System Design Primer', 'markdown', 'Walk through requirements, capacity, identifiers, storage, and scaling a short-link service.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:notifications', 'systemdesign', 16, 'Case study: notification service', 'https://www.rabbitmq.com/docs/confirms', 'https://www.rabbitmq.com/docs/confirms', 'RabbitMQ', 'html', 'Design durable notification delivery with retries, acknowledgements, and deduplication.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:news-feed', 'systemdesign', 17, 'Case study: news feed', 'https://github.com/donnemartin/system-design-primer/blob/master/solutions/system_design/twitter/README.md', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/solutions/system_design/twitter/README.md', 'System Design Primer', 'markdown', 'Explain feed generation, fanout choices, read/write trade-offs, and bottlenecks.', NULL);
INSERT OR IGNORE INTO chapters (id, topic, position, title, url, text_url, source, format, objective, sections)
VALUES ('systemdesign:tradeoffs', 'systemdesign', 18, 'Revisit designs under changing constraints', 'https://github.com/donnemartin/system-design-primer', 'https://raw.githubusercontent.com/donnemartin/system-design-primer/master/README.md', 'System Design Primer', 'markdown', 'Compare architecture choices as traffic, data volume, and consistency requirements change.', '["Performance vs scalability"]');
